# Generated by Django 3.0.8 on 2020-08-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='billingProfile',
            new_name='billing_profile',
        ),
    ]
