# Generated by Django 3.0.8 on 2020-09-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20200915_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='brand',
            new_name='currency',
        ),
    ]
