# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-08-26 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20171012_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='billing_profile',
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='customer_id',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
