# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-09-21 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200921_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='updated',
            new_name='update',
        ),
        migrations.RemoveField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
        ),
    ]
