# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-02 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productpurchase_productpurchasemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
            preserve_default=False,
        ),
    ]
