# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productpurchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='user',
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='order',
            field=models.CharField(max_length=120),
        ),
    ]
