# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201002_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpurchase',
            old_name='order',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
