# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-10-03 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_productfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductFile',
        ),
    ]
